### ISSUE TITLE
cannot install vcfR to ubuntu

### ISSUE THREAD

**Issue by JanSliacky** [knausb/vcfR_documentation#2]
Cannot install vcfR into Rstudio on ubuntu.

Ubuntu version:
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"

Rstudio version 
2023.03.0+386

R version

R version 4.2.1 (2022-06-23) -- "Funny-Looking Kid"

Would it be possible to fix it or find a workaround?

**Comment by JanSliacky** [comment]
Here is the output from terminal:
> install.packages("vcfR")
Installing package into ‘/home/kovac/R/x86_64-pc-linux-gnu-library/4.2’
(as ‘lib’ is unspecified)
also installing the dependencies ‘ape’, ‘vegan’

trying URL 'https://cloud.r-project.org/src/contrib/ape_5.7-1.tar.gz'
Content type 'application/x-gzip' length 1577273 bytes (1.5 MB)
==================================================
downloaded 1.5 MB

trying URL 'https://cloud.r-project.org/src/contrib/vegan_2.6-4.tar.gz'
Content type 'application/x-gzip' length 1496110 bytes (1.4 MB)
==================================================
downloaded 1.4 MB

trying URL 'https://cloud.r-project.org/src/contrib/vcfR_1.14.0.tar.gz'
Content type 'application/x-gzip' length 1456499 bytes (1.4 MB)
==================================================
downloaded 1.4 MB

* installing *source* package ‘ape’ ...
** package ‘ape’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
gcc -I"/usr/share/R/include" -DNDEBUG  -I'/home/kovac/R/x86_64-pc-linux-gnu-libr                                                                                                                                                                                                                                             ary/4.2/Rcpp/include'    -fpic  -g -O2 -ffile-prefix-map=/build/r-base-Ff4YNH/r-                                                                                                                                                                                                                                             base-4.2.1=. -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Wer                                                                                                                                                                                                                                             ror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c BIONJ.c -o BIONJ.o
gcc -I"/usr/share/R/include" -DNDEBUG  -I'/home/kovac/R/x86_64-pc-linux-gnu-libr                                                                                                                                                                                                                                             ary/4.2/Rcpp/include'    -fpic  -g -O2 -ffile-prefix-map=/build/r-base-Ff4YNH/r-                                                                                                                                                                                                                                             base-4.2.1=. -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Wer                                                                                                                                                                                                                                             ror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c NNI.c -o NNI.o
g++ -std=gnu++14 -I"/usr/share/R/include" -DNDEBUG  -I'/home/kovac/R/x86_64-pc-l                                                                                                                                                                                                                                             inux-gnu-library/4.2/Rcpp/include'    -fpic  -g -O2 -ffile-prefix-map=/build/r-b                                                                                                                                                                                                                                             ase-Ff4YNH/r-base-4.2.1=. -flto=auto -ffat-lto-objects -fstack-protector-strong                                                                                                                                                                                                                                              -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c RcppExports                                                                                                                                                                                                                                             .cpp -o RcppExports.o
gcc -I"/usr/share/R/include" -DNDEBUG  -I'/home/kovac/R/x86_64-pc-linux-gnu-libr                                                                                                                                                                                                                                             ary/4.2/Rcpp/include'    -fpic  -g -O2 -ffile-prefix-map=/build/r-base-Ff4YNH/r-                                                                                                                                                                                                                                             base-4.2.1=. -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Wer                                                                                                                                                                                                                                             ror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c SPR.c -o SPR.o
gcc -I"/usr/share/R/include" -DNDEBUG  -I'/home/kovac/R/x86_64-pc-linux-gnu-libr                                                                                                                                                                                                                                             ary/4.2/Rcpp/include'    -fpic  -g -O2 -ffile-prefix-map=/build/r-base-Ff4YNH/r-                                                                                                                                                                                                                                             base-4.2.1=. -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Wer                                                                                                                                                                                                                                             ror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c additive.c -o additive.o
gcc -I"/usr/share/R/include" -DNDEBUG  -I'/home/kovac/R/x86_64-pc-linux-gnu-libr                                                                                                                                                                                                                                             ary/4.2/Rcpp/include'    -fpic  -g -O2 -ffile-prefix-map=/build/r-base-Ff4YNH/r-                                                                                                                                                                                                                                             base-4.2.1=. -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Wer                                                                                                                                                                                                                                             ror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c ape.c -o ape.o
gcc -I"/usr/share/R/include" -DNDEBUG  -I'/home/kovac/R/x86_64-pc-linux-gnu-libr                                                                                                                                                                                                                                             ary/4.2/Rcpp/include'    -fpic  -g -O2 -ffile-prefix-map=/build/r-base-Ff4YNH/r-                                                                                                                                                                                                                                             base-4.2.1=. -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Wer                                                                                                                                                                                                                                             ror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c bNNI.c -o bNNI.o
gcc -I"/usr/share/R/include" -DNDEBUG  -I'/home/kovac/R/x86_64-pc-linux-gnu-libr                                                                                                                                                                                                                                             ary/4.2/Rcpp/include'    -fpic  -g -O2 -ffile-prefix-map=/build/r-base-Ff4YNH/r-                                                                                                                                                                                                                                             base-4.2.1=. -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Wer                                                                                                                                                                                                                                             ror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c bionjs.c -o bionjs.o
gcc -I"/usr/share/R/include" -DNDEBUG  -I'/home/kovac/R/x86_64-pc-linux-gnu-libr                                                                                                                                                                                                                                             ary/4.2/Rcpp/include'    -fpic  -g -O2 -ffile-prefix-map=/build/r-base-Ff4YNH/r-                                                                                                                                                                                                                                             base-4.2.1=. -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Wer                                                                                                                                                                                                                                             ror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c bipartition.c -o biparti                                                                                                                                                                                                                                             tion.o
gcc -I"/usr/share/R/include" -DNDEBUG  -I'/home/kovac/R/x86_64-pc-linux-gnu-libr                                                                                                                                                                                                                                             ary/4.2/Rcpp/include'    -fpic  -g -O2 -ffile-prefix-map=/build/r-base-Ff4YNH/r-                                                                                                                                                                                                                                             base-4.2.1=. -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Wer                                                                                                                                                                                                                                             ror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c bitsplits.c -o bitsplits                                                                                                                                                                                                                                             .o
gcc -I"/usr/share/R/include" -DNDEBUG  -I'/home/kovac/R/x86_64-pc-linux-gnu-libr                                                                                                                                                                                                                                             ary/4.2/Rcpp/include'    -fpic  -g -O2 -ffile-prefix-map=/build/r-base-Ff4YNH/r-                                                                                                                                                                                                                                             base-4.2.1=. -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Wer                                                                                                                                                                                                                                             ror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c delta_plot.c -o delta_pl                                                                                                                                                                                                                                             ot.o
gcc -I"/usr/share/R/include" -DNDEBUG  -I'/home/kovac/R/x86_64-pc-linux-gnu-libr                                                                                                                                                                                                                                             ary/4.2/Rcpp/include'    -fpic  -g -O2 -ffile-prefix-map=/build/r-base-Ff4YNH/r-                                                                                                                                                                                                                                             base-4.2.1=. -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Wer                                                                                                                                                                                                                                             ror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c dist_dna.c -o dist_dna.o
gcc -I"/usr/share/R/include" -DNDEBUG  -I'/home/kovac/R/x86_64-pc-linux-gnu-libr                                                                                                                                                                                                                                             ary/4.2/Rcpp/include'    -fpic  -g -O2 -ffile-prefix-map=/build/r-base-Ff4YNH/r-                                                                                                                                                                                                                                             base-4.2.1=. -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Wer                                                                                                                                                                                                                                             ror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c dist_nodes.c -o dist_nod                                                                                                                                                                                                                                             es.o
gcc -I"/usr/share/R/include" -DNDEBUG  -I'/home/kovac/R/x86_64-pc-linux-gnu-libr                                                                                                                                                                                                                                             ary/4.2/Rcpp/include'    -fpic  -g -O2 -ffile-prefix-map=/build/r-base-Ff4YNH/r-                                                                                                                                                                                                                                             base-4.2.1=. -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Wer                                                                                                                                                                                                                                             ror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c ewLasso.c -o ewLasso.o
gcc -I"/usr/share/R/include" -DNDEBUG  -I'/home/kovac/R/x86_64-pc-linux-gnu-libr                                                                                                                                                                                                                                             ary/4.2/Rcpp/include'    -fpic  -g -O2 -ffile-prefix-map=/build/r-base-Ff4YNH/r-                                                                                                                                                                                                                                             base-4.2.1=. -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Wer                                                                                                                                                                                                                                             ror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c heap.c -o heap.o
gcc -I"/usr/share/R/include" -DNDEBUG  -I'/home/kovac/R/x86_64-pc-linux-gnu-libr                                                                                                                                                                                                                                             ary/4.2/Rcpp/include'    -fpic  -g -O2 -ffile-prefix-map=/build/r-base-Ff4YNH/r-                                                                                                                                                                                                                                             base-4.2.1=. -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Wer                                                                                                                                                                                                                                             ror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c mat_expo.c -o mat_expo.o
gcc -I"/usr/share/R/include" -DNDEBUG  -I'/home/kovac/R/x86_64-pc-linux-gnu-libr                                                                                                                                                                                                                                             ary/4.2/Rcpp/include'    -fpic  -g -O2 -ffile-prefix-map=/build/r-base-Ff4YNH/r-                                                                                                                                                                                                                                             base-4.2.1=. -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Wer                                                                                                                                                                                                                                             ror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c me.c -o me.o
gcc -I"/usr/share/R/include" -DNDEBUG  -I'/home/kovac/R/x86_64-pc-linux-gnu-libr                                                                                                                                                                                                                                             ary/4.2/Rcpp/include'    -fpic  -g -O2 -ffile-prefix-map=/build/r-base-Ff4YNH/r-                                                                                                                                                                                                                                             base-4.2.1=. -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Wer                                                                                                                                                                                                                                             ror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c me_balanced.c -o me_bala                                                                                                                                                                                                                                             nced.o
gcc -I"/usr/share/R/include" -DNDEBUG  -I'/home/kovac/R/x86_64-pc-linux-gnu-libr                                                                                                                                                                                                                                             ary/4.2/Rcpp/include'    -fpic  -g -O2 -ffile-prefix-map=/build/r-base-Ff4YNH/r-                                                                                                                                                                                                                                             base-4.2.1=. -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Wer                                                                                                                                                                                                                                             ror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c me_ols.c -o me_ols.o
gcc -I"/usr/share/R/include" -DNDEBUG  -I'/home/kovac/R/x86_64-pc-linux-gnu-libr                                                                                                                                                                                                                                             ary/4.2/Rcpp/include'    -fpic  -g -O2 -ffile-prefix-map=/build/r-base-Ff4YNH/r-                                                                                                                                                                                                                                             base-4.2.1=. -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Wer                                                                                                                                                                                                                                             ror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c mvr.c -o mvr.o
gcc -I"/usr/share/R/include" -DNDEBUG  -I'/home/kovac/R/x86_64-pc-linux-gnu-libr                                                                                                                                                                                                                                             ary/4.2/Rcpp/include'    -fpic  -g -O2 -ffile-prefix-map=/build/r-base-Ff4YNH/r-                                                                                                                                                                                                                                             base-4.2.1=. -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Wer                                                                                                                                                                                                                                             ror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c mvrs.c -o mvrs.o
gcc -I"/usr/share/R/include" -DNDEBUG  -I'/home/kovac/R/x86_64-pc-linux-gnu-libr                                                                                                                                                                                                                                             ary/4.2/Rcpp/include'    -fpic  -g -O2 -ffile-prefix-map=/build/r-base-Ff4YNH/r-                                                                                                                                                                                                                                             base-4.2.1=. -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Wer                                                                                                                                                                                                                                             ror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c nj.c -o nj.o
gcc -I"/usr/share/R/include" -DNDEBUG  -I'/home/kovac/R/x86_64-pc-linux-gnu-libr                                                                                                                                                                                                                                             ary/4.2/Rcpp/include'    -fpic  -g -O2 -ffile-prefix-map=/build/r-base-Ff4YNH/r-                                                                                                                                                                                                                                             base-4.2.1=. -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Wer                                                                                                                                                                                                                                             ror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c njs.c -o njs.o
gcc -I"/usr/share/R/include" -DNDEBUG  -I'/home/kovac/R/x86_64-pc-linux-gnu-libr                                                                                                                                                                                                                                             ary/4.2/Rcpp/include'    -fpic  -g -O2 -ffile-prefix-map=/build/r-base-Ff4YNH/r-                                                                                                                                                                                                                                             base-4.2.1=. -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Wer                                                                                                                                                                                                                                             ror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c pic.c -o pic.o
gcc -I"/usr/share/R/include" -DNDEBUG  -I'/home/kovac/R/x86_64-pc-linux-gnu-libr                                                                                                                                                                                                                                             ary/4.2/Rcpp/include'    -fpic  -g -O2 -ffile-prefix-map=/build/r-base-Ff4YNH/r-                                                                                                                                                                                                                                             base-4.2.1=. -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Wer                                                                                                                                                                                                                                             ror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c plot_phylo.c -o plot_phy                                                                                                                                                                                                                                             lo.o
g++ -std=gnu++14 -I"/usr/share/R/include" -DNDEBUG  -I'/home/kovac/R/x86_64-pc-l                                                                                                                                                                                                                                             inux-gnu-library/4.2/Rcpp/include'    -fpic  -g -O2 -ffile-prefix-map=/build/r-b                                                                                                                                                                                                                                             ase-Ff4YNH/r-base-4.2.1=. -flto=auto -ffat-lto-objects -fstack-protector-strong                                                                                                                                                                                                                                              -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c prop_part.c                                                                                                                                                                                                                                             pp -o prop_part.o
gcc -I"/usr/share/R/include" -DNDEBUG  -I'/home/kovac/R/x86_64-pc-linux-gnu-libr                                                                                                                                                                                                                                             ary/4.2/Rcpp/include'    -fpic  -g -O2 -ffile-prefix-map=/build/r-base-Ff4YNH/r-                                                                                                                                                                                                                                             base-4.2.1=. -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Wer                                                                                                                                                                                                                                             ror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c rTrait.c -o rTrait.o
gcc -I"/usr/share/R/include" -DNDEBUG  -I'/home/kovac/R/x86_64-pc-linux-gnu-libr                                                                                                                                                                                                                                             ary/4.2/Rcpp/include'    -fpic  -g -O2 -ffile-prefix-map=/build/r-base-Ff4YNH/r-                                                                                                                                                                                                                                             base-4.2.1=. -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Wer                                                                                                                                                                                                                                             ror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c read_dna.c -o read_dna.o
g++ -std=gnu++14 -I"/usr/share/R/include" -DNDEBUG  -I'/home/kovac/R/x86_64-pc-l                                                                                                                                                                                                                                             inux-gnu-library/4.2/Rcpp/include'    -fpic  -g -O2 -ffile-prefix-map=/build/r-b                                                                                                                                                                                                                                             ase-Ff4YNH/r-base-4.2.1=. -flto=auto -ffat-lto-objects -fstack-protector-strong                                                                                                                                                                                                                                              -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c reorder_Rcp                                                                                                                                                                                                                                             p.cpp -o reorder_Rcpp.o
gcc -I"/usr/share/R/include" -DNDEBUG  -I'/home/kovac/R/x86_64-pc-linux-gnu-libr                                                                                                                                                                                                                                             ary/4.2/Rcpp/include'    -fpic  -g -O2 -ffile-prefix-map=/build/r-base-Ff4YNH/r-                                                                                                                                                                                                                                             base-4.2.1=. -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Wer                                                                                                                                                                                                                                             ror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c reorder_phylo.c -o reord                                                                                                                                                                                                                                             er_phylo.o
gcc -I"/usr/share/R/include" -DNDEBUG  -I'/home/kovac/R/x86_64-pc-linux-gnu-libr                                                                                                                                                                                                                                             ary/4.2/Rcpp/include'    -fpic  -g -O2 -ffile-prefix-map=/build/r-base-Ff4YNH/r-                                                                                                                                                                                                                                             base-4.2.1=. -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Wer                                                                                                                                                                                                                                             ror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c treePop.c -o treePop.o
gcc -I"/usr/share/R/include" -DNDEBUG  -I'/home/kovac/R/x86_64-pc-linux-gnu-libr                                                                                                                                                                                                                                             ary/4.2/Rcpp/include'    -fpic  -g -O2 -ffile-prefix-map=/build/r-base-Ff4YNH/r-                                                                                                                                                                                                                                             base-4.2.1=. -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Wer                                                                                                                                                                                                                                             ror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c tree_build.c -o tree_bui                                                                                                                                                                                                                                             ld.o
gcc -I"/usr/share/R/include" -DNDEBUG  -I'/home/kovac/R/x86_64-pc-linux-gnu-libr                                                                                                                                                                                                                                             ary/4.2/Rcpp/include'    -fpic  -g -O2 -ffile-prefix-map=/build/r-base-Ff4YNH/r-                                                                                                                                                                                                                                             base-4.2.1=. -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Wer                                                                                                                                                                                                                                             ror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c tree_phylo.c -o tree_phy                                                                                                                                                                                                                                             lo.o
gcc -I"/usr/share/R/include" -DNDEBUG  -I'/home/kovac/R/x86_64-pc-linux-gnu-libr                                                                                                                                                                                                                                             ary/4.2/Rcpp/include'    -fpic  -g -O2 -ffile-prefix-map=/build/r-base-Ff4YNH/r-                                                                                                                                                                                                                                             base-4.2.1=. -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Wer                                                                                                                                                                                                                                             ror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c triangMtd.c -o triangMtd                                                                                                                                                                                                                                             .o
gcc -I"/usr/share/R/include" -DNDEBUG  -I'/home/kovac/R/x86_64-pc-linux-gnu-libr                                                                                                                                                                                                                                             ary/4.2/Rcpp/include'    -fpic  -g -O2 -ffile-prefix-map=/build/r-base-Ff4YNH/r-                                                                                                                                                                                                                                             base-4.2.1=. -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Wer                                                                                                                                                                                                                                             ror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c triangMtds.c -o triangMt                                                                                                                                                                                                                                             ds.o
gcc -I"/usr/share/R/include" -DNDEBUG  -I'/home/kovac/R/x86_64-pc-linux-gnu-libr                                                                                                                                                                                                                                             ary/4.2/Rcpp/include'    -fpic  -g -O2 -ffile-prefix-map=/build/r-base-Ff4YNH/r-                                                                                                                                                                                                                                             base-4.2.1=. -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Wer                                                                                                                                                                                                                                             ror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c ultrametric.c -o ultrame                                                                                                                                                                                                                                             tric.o
g++ -std=gnu++14 -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -flto=auto -W                                                                                                                                                                                                                                             l,-z,relro -o ape.so BIONJ.o NNI.o RcppExports.o SPR.o additive.o ape.o bNNI.o b                                                                                                                                                                                                                                             ionjs.o bipartition.o bitsplits.o delta_plot.o dist_dna.o dist_nodes.o ewLasso.o                                                                                                                                                                                                                                              heap.o mat_expo.o me.o me_balanced.o me_ols.o mvr.o mvrs.o nj.o njs.o pic.o plo                                                                                                                                                                                                                                             t_phylo.o prop_part.o rTrait.o read_dna.o reorder_Rcpp.o reorder_phylo.o treePop                                                                                                                                                                                                                                             .o tree_build.o tree_phylo.o triangMtd.o triangMtds.o ultrametric.o -llapack -lb                                                                                                                                                                                                                                             las -lgfortran -lm -lquadmath -L/usr/lib/R/lib -lR
/usr/bin/ld: cannot find -llapack: No such file or directory
/usr/bin/ld: cannot find -lblas: No such file or directory
collect2: error: ld returned 1 exit status
make: *** [/usr/share/R/share/make/shlib.mk:10: ape.so] Error 1
ERROR: compilation failed for package ‘ape’
* removing ‘/home/kovac/R/x86_64-pc-linux-gnu-library/4.2/ape’
* installing *source* package ‘vegan’ ...
** package ‘vegan’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
gcc -I"/usr/share/R/include" -DNDEBUG      -fpic  -g -O2 -ffile-prefix-map=/buil                                                                                                                                                                                                                                             d/r-base-Ff4YNH/r-base-4.2.1=. -flto=auto -ffat-lto-objects -fstack-protector-st                                                                                                                                                                                                                                             rong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c data2h                                                                                                                                                                                                                                             ill.c -o data2hill.o
gfortran -fno-optimize-sibling-calls  -fpic  -g -O2 -ffile-prefix-map=/build/r-b                                                                                                                                                                                                                                             ase-Ff4YNH/r-base-4.2.1=. -flto=auto -ffat-lto-objects -fstack-protector-strong                                                                                                                                                                                                                                               -c decorana.f -o decorana.o
/bin/bash: line 1: gfortran: command not found
make: *** [/usr/lib/R/etc/Makeconf:191: decorana.o] Error 127
ERROR: compilation failed for package ‘vegan’
* removing ‘/home/kovac/R/x86_64-pc-linux-gnu-library/4.2/vegan’
ERROR: dependencies ‘ape’, ‘vegan’ are not available for package ‘vcfR’
* removing ‘/home/kovac/R/x86_64-pc-linux-gnu-library/4.2/vcfR’

The downloaded source packages are in
        ‘/tmp/RtmpDOAUse/downloaded_packages’
Warning messages:
1: In install.packages("vcfR") :
  installation of package ‘ape’ had non-zero exit status
2: In install.packages("vcfR") :
  installation of package ‘vegan’ had non-zero exit status
3: In install.packages("vcfR") :
  installation of package ‘vcfR’ had non-zero exit status
> library(vcfR)
Error in library(vcfR) : there is no package called ‘vcfR’

**Comment by knausb** [comment]
Hi, this does not appear to be a vcfR issue. It appears the installation of ape has failed. I think this may be because your system is lacking libraries.

/usr/bin/ld: cannot find -llapack: No such file or directory
/usr/bin/ld: cannot find -lblas: No such file or directory

Try googling something like 'ubuntu install llapack' to install the libraries, try install.packages('ape'), and if that all works, try installing vcfR again.

**Comment by JanSliacky** [comment]
Many thanks, that was the issue. I installed llapack and then ape and vegan. Now the install of vcfR was without any problem. You saved a huge amount of my time, thank you.
